/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SessionEvent =
  | FileEditedEvent
  | NoteAddedEvent
  | ControlClaimedEvent
  | ControlReleasedEvent
  | ViewerJoinedEvent
  | ViewerLeftEvent
  | SessionFailedEvent
  | SessionStartedEvent
  | AgentPromptSubmittedEvent
  | AgentSteeredEvent
  | AgentAbortedEvent
  | AgentRunStartedEvent
  | AgentTextDeltaEvent
  | AgentRunFinishedEvent
  | AgentRunFailedEvent;
export type Content = string;
export type EditorId = string;
export type Path = string;
export type SessionId = string;
export type Type = "file_edited";
export type AuthorId = string;
export type Body = string;
export type CreatedAt = number;
export type SessionId1 = string;
export type Type1 = "note_added";
export type SessionId2 = string;
export type Type2 = "control_claimed";
export type UserId = string;
export type SessionId3 = string;
export type Type3 = "control_released";
export type UserId1 = string;
export type SessionId4 = string;
export type Type4 = "viewer_joined";
export type UserId2 = string;
export type SessionId5 = string;
export type Type5 = "viewer_left";
export type UserId3 = string;
export type Error = string;
export type SessionId6 = string;
export type Type6 = "session_failed";
export type AgentSessionId = string;
export type SessionId7 = string;
export type Type7 = "session_started";
export type WorkspacePath = string;
export type SessionId8 = string;
export type Text = string;
export type Type8 = "agent_prompt_submitted";
export type UserId4 = string;
export type SessionId9 = string;
export type Text1 = string;
export type Type9 = "agent_steered";
export type UserId5 = string;
export type SessionId10 = string;
export type Type10 = "agent_aborted";
export type UserId6 = string;
export type SessionId11 = string;
export type Type11 = "agent_run_started";
export type Delta = string;
export type SessionId12 = string;
export type Type12 = "agent_text_delta";
export type SessionId13 = string;
export type Type13 = "agent_run_finished";
export type Command = string | null;
export type Error1 = string;
export type SessionId14 = string;
export type Type14 = "agent_run_failed";

export interface FileEditedEvent {
  content: Content;
  editor_id: EditorId;
  path: Path;
  session_id: SessionId;
  type: Type;
}
export interface NoteAddedEvent {
  author_id: AuthorId;
  body: Body;
  created_at: CreatedAt;
  session_id: SessionId1;
  type: Type1;
}
export interface ControlClaimedEvent {
  session_id: SessionId2;
  type: Type2;
  user_id: UserId;
}
export interface ControlReleasedEvent {
  session_id: SessionId3;
  type: Type3;
  user_id: UserId1;
}
export interface ViewerJoinedEvent {
  session_id: SessionId4;
  type: Type4;
  user_id: UserId2;
}
export interface ViewerLeftEvent {
  session_id: SessionId5;
  type: Type5;
  user_id: UserId3;
}
export interface SessionFailedEvent {
  error: Error;
  session_id: SessionId6;
  type: Type6;
}
export interface SessionStartedEvent {
  agent_session_id: AgentSessionId;
  session_id: SessionId7;
  type: Type7;
  workspace_path: WorkspacePath;
}
export interface AgentPromptSubmittedEvent {
  session_id: SessionId8;
  text: Text;
  type: Type8;
  user_id: UserId4;
}
export interface AgentSteeredEvent {
  session_id: SessionId9;
  text: Text1;
  type: Type9;
  user_id: UserId5;
}
export interface AgentAbortedEvent {
  session_id: SessionId10;
  type: Type10;
  user_id: UserId6;
}
export interface AgentRunStartedEvent {
  session_id: SessionId11;
  type: Type11;
}
export interface AgentTextDeltaEvent {
  delta: Delta;
  session_id: SessionId12;
  type: Type12;
}
export interface AgentRunFinishedEvent {
  session_id: SessionId13;
  type: Type13;
}
export interface AgentRunFailedEvent {
  command?: Command;
  error: Error1;
  session_id: SessionId14;
  type: Type14;
}
